# Generated by Django 3.0.3 on 2020-02-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disorders', models.ManyToManyField(to='disorders.Disorder')),
            ],
        ),
    ]
