# Generated by Django 3.0.3 on 2020-03-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disorders', '0003_queryform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryForm',
        ),
    ]
